import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { Nunito } from 'next/font/google';
import { Provider } from "@/components/ui/provider"
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

const nunito = Nunito({ 
  variable: "--font-nunito",
  subsets: ['latin', 'latin-ext'], 
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  display: 'swap', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
